export const SEARCH_ARTIST_INIT = 'SEARCH_ARTIST_INIT'
export const SEARCH_ARTIST_SUCESS = 'SEARCH_ARTIST_SUCCESS'
export const SEARCH_ARTIST_ERROR = 'SEARCH_ARTIST_ERROR'

export const SEARCH_TRACK_INIT = 'SEARCH_TRACK_INIT'
export const SEARCH_TRACK_SUCESS = 'SEARCH_TRACK_SUCESS'
export const SEARCH_TRACK_ERROR = 'SEARCH_TRACK_ERROR'

export const NEXT_PAG_ARTIST = 'NEXT_PAG_ARTIST'
export const PREV_PAG_ARTIST = 'PREV_PAG_ARTIST'
export const INIT_PAG_ARTIST = 'INIT_PAG_ARTIST'
export const CHANGE_PAG_ARTIST_ERROR = 'CHANGE_PAG_ARTIST_ERROR'

export const NEXT_PAG_TRACK = 'NEXT_PAG_TRACK'
export const PREV_PAG_TRACK = 'PREV_PAG_TRACK'
export const INIT_PAG_TRACK = 'INIT_PAG_TRACK'
export const CHANGE_PAG_TRACK_ERROR = 'CHANGE_PAG_TRACK_ERROR'
