export const SEARCH_ARTIST_INIT = 'SEARCH_ARTIST_INIT'
export const SEARCH_ARTIST_SUCESS = 'SEARCH_ARTIST_SUCCESS'
export const SEARCH_ARTIST_ERROR = 'SEARCH_ARTIST_ERROR'

export const SEARCH_TRACK_INIT = 'SEARCH_TRACK_INIT'
export const SEARCH_TRACK_SUCESS = 'SEARCH_TRACK_SUCESS'
export const SEARCH_TRACK_ERROR = 'SEARCH_TRACK_ERROR'
