export const FETCH_ALBUMS_INIT = 'FETCH_ALBUMS_INIT'
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS'
export const FETCH_ALBUMS_ERROR = 'FETCH_ALBUMS_ERROR'

export const NEXT_PAG_NEW_RELEASES = 'NEXT_PAG_NEW_RELEASES'
export const PREV_PAG_NEW_RELEASES = 'PREV_PAG_NEW_RELEASES'
export const INIT_PAG_NEW_RELEASES = 'INIT_PAG_NEW_RELEASES'
export const CHANGE_PAG_NEW_RELEASES_ERROR = 'CHANGE_PAG_NEW_RELEASES_ERROR'
