export const FETCH_TOKEN_INIT = 'FETCH_TOKEN'
export const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS'
export const FETCH_TOKEN_ERROR = 'FETCH_TOKEN_ERROR'

export const REFRESH_TOKEN = 'REFRESH_TOKEN'
export const CLEAR_STORAGE = 'CLEAR_STORAGE'
